  services:
  db:
    image: mysql:8.0.44
    container_name: semijoia-db
    restart: always
    environment:
      MYSQL_DATABASE: semijoia_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: dev_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data: